#ifndef CGOL_CONSTANTS_H
#define CGOL_CONSTANTS_H

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 900
#define TARGET_FPS 60
#define GRID_THICKNESS (0.5)

#define CHUNK_SIZE 128

#define CELL_WORLD_SIZE 25
#define CHUNK_WORLD_SIZE (CHUNK_SIZE*CELL_WORLD_SIZE)
#define STEP_TIME_INTERVAL (1000.0f/12.0f)

#define FONT_SIZE 32
#define FONT_PADDING 16

#define CDA_INITAL_CAPACITY (32)
#define CDA_GROWTH_FACTOR (1.5)



#endif //CGOL_CONSTANTS_H
