#ifndef CGOL_CONSTANTS_H
#define CGOL_CONSTANTS_H

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 900
#define GRID_THICKNESS 2
#define CELL_WORLD_SIZE 50
#define CHUNK_SIZE 16
#define CHUNK_WORLD_SIZE (CHUNK_SIZE*CELL_WORLD_SIZE)

#endif //CGOL_CONSTANTS_H